//可以用throw函数抛出的对象类型
public interface Throwable
{
    public String str();
}

//抛出异常
public native void throw(Throwable t);

//捕获语法返回的对象：抛出的对象+traceback的组合
//定义：Catched<Throwable>是所有Catched对象的base
public class Catched<T>
{
    Catched(T t, String tb)
    {
        this.t = t;
        this.tb = tb;
    }

    public void rethrow()
    {
        rethrow_catched(new Catched<Throwable>(this.t, this.tb));
    }

    public T throwed()
    {
        return this.t;
    }

    public String traceback()
    {
        return this.tb;
    }

    T t;
    String tb;
}

//继续往上抛当前Catched对象，维持对象不变，即和再次throw的区别在于traceback可以保持不变
native void rethrow_catched(Catched<Throwable> c);

//assert函数
public void assert(bool b, String s)
{
    if (!b)
    {
        throw(new AssertError(s));
    }
}

//--------------------------------------------------------------------

/*
下面的catch相关的代码较为特殊，编译器会在代码生成阶段做一些特殊修改
主要原因在于：go规定recover必须在defer func中直接执行，即直接defer recover()或在defer func中调用的函数里用recover都无法捕获panic
因此必须在larva调用下面两个catch函数的时候，同时调用recover并将结果传进来，但语法上让程序员无感知
编译器的大致处理步骤就是在代码生成部分对这两个catch增加参数（定义和调用都需要调整），为了对代码实现影响最小，用了一个假的全局变量欺骗语法检查
相关trick代码元素都以下划线开头，以示区别
*/

Any _go_recovered;

native Catched<Throwable> _go_recovered_to_catched(Any _r);

//捕获base
public Catched<Throwable> catch_base(/*Any _go_recovered*/)
{
    return _go_recovered_to_catched(_go_recovered);
}

//捕获指定类型的异常
public Catched<T> catch<T>(/*Any _go_recovered*/)
{
    var c = _go_recovered_to_catched(_go_recovered);
    if (c == nil)
    {
        //无异常
        return nil;
    }
    T throwed;
    if (is_same_type(c.throwed(), throwed))
    {
        throwed = (T)c.throwed();
    }
    else
    {
        //不是当前需要的类型，继续往上抛
        c.rethrow();
    }
    return new Catched<T>(throwed, c.traceback());
}

//---------------------------------------------------------------------

//一个基本的常用异常的实现：仅包含一个字符串info
public class Exception
{
    public Exception(String s)
    {
        this.info = s;
    }

    String info usemethod(str);
}

//这里是通用的一些内建异常类型

//Assert错误，只用于assert
public class AssertError
{
    public AssertError(String s)
    {
        this.e = new Exception(s);
    }

    Exception e usemethod;
}

//运行时类型转换（从接口到类型或其他接口）失败的错误
public class CastError
{
    public String str()
    {
        return "";
    }
}

//索引（下标）错误，用于数组、Slice、Vector等可用下标定位元素的相关代码中
public class IndexError
{
    public IndexError(long i)
    {
        this.has_idx = true;
        this.idx = i;
    }

    public String str()
    {
        if (this.has_idx)
        {
            return "%d".(this.idx);
        }
        else
        {
            return "<none>";
        }
    }

    bool has_idx;
    long idx;
}

//下标范围错误，用于slice、sub_str之类的取范围相关代码
public class RangeError
{
    public RangeError(long l, long b, long e)
    {
        this.has_range_info = true;
        this.len = l;
        this.begin = b;
        this.end = e;
    }

    public String str()
    {
        if (this.has_range_info)
        {
            return "[%d][%d:%d]".(this.len, this.begin, this.end);
        }
        else
        {
            return "<none>";
        }
    }

    bool has_range_info;
    long len;
    long begin;
    long end;
}

//通用的下标检查，检查不通过则抛出RangeError
public void check_range(long l, long b, long e)
{
    if (l < 0 || b < 0 || b > l || e < b || e > l)
    {
        throw(new RangeError(l, b, e));
    }
}

//键错误，用于各种映射、集合等用到Key的地方，k为错误的键的字符串描述
public class KeyError
{
    public KeyError(String k)
    {
        this.e = new Exception(k);
    }

    Exception e usemethod;
}

//值错误，用于根据值解析、查找等操作的地方，v为错误的值的字符串描述
public class ValueError
{
    public ValueError(String v)
    {
        this.e = new Exception(v);
    }

    Exception e usemethod;
}

//超时错误，用于操作超时时抛出
public class TimeoutError
{
    public TimeoutError()
    {
    }

    public String str()
    {
        return "";
    }
}

//go的error类型的一个port，用于一些native代码从error到异常的转换
public native class GoError
{
    public String str();
    public GoError go_err();
}

public interface GoErrorPorter
{
    public GoError go_err();
}
